apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  # namespace : lannisters
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 580572941932.dkr.ecr.ap-south-1.amazonaws.com/lannisters_repo_webapp:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        # image: webapp
        # imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  # namespace : lannisters
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    type: LoadBalancer
  ports:
    # - name: http
      #port: 80
      #nodePort: 30080
    - protocol: TCP
      port: 80
      targetPort: 80

  # type: NodePort